baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Kuro's Weblog"
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
defaultTheme = 'light'
ShowReadingTime = true

    [params.homeInfoParams]
    Title = "Hi there wave"
    Content = "Can be Info, links, about..."

    [[params.socialIcons]]
    name = "<platform>"
    url = "<link>"

    [[params.socialIcons]]
    name = "<platform 2>"
    url = "<link2>"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20
[[menu.main]]
    name = "Archives"
    url = "/archives"
    weight = 30
[[menu.main]]
    name = "Search"
    url = "/search"
    weight = 40